# Input:          Original read files in FASTQ format that are generated by illumina sequencing
#                 (s_8_1_sequence.txt)
# What it does:   For use with single end reads where pairing is not needed. Finds reads with a given barcode, writes them to a new file. 
# How it does it: Goes through the file line by line, looks for the barcode, writes read to a new file if barcode matches.
# Output:         A text file that has one read per line (no particular file format).



#Enter file names and barcode sequence below.
nameof_inputfile="Sample_1_NoIndex_L001_R1_001.fastq"
nameof_outputfile="20170111_All_DNA.txt"
#barcode="TTC"   # Barcode sequence has to be in capital letters.
#               Enter from left to right as it appears in the read.

#barcode_starting_position=4  #Which position in the read has the first letter of the barcode.

#-------------------------------------------------------------------------------------


inputfile = open(nameof_inputfile)
outputfile = open(nameof_outputfile, "w")

#barcodelength = len(barcode)
#barcode_firstresidue = barcode_starting_position-1 #1st residue is the 0th element of the string. This adjusts for that.
#barcode_lastresidue = barcode_firstresidue + barcodelength

i=-1
for line in inputfile:
        if i%4==0:
##                if line[barcode_firstresidue:barcode_lastresidue]==barcode: #looking for barcode
                    outputfile.write(line)

        i=i+1
outputfile.close()


    
